return table.freeze({
    ["Restock"] = 3524818685,

    -- Robux Shop
    ["Starter Pack"] = 3524815054,
    ["Pro Pack"] = 3524815166,
    ["Frigo Camelo"] = 3527110390,
    ["Six Seven"] = 3527110462,
    ["Esok Sekolah"] = 3527110515,
    ["Small Pack"] = 3525605432,
    ["Medium Pack"] = 3525605287,
    ["Huge Pack"] = 3524820157,

    -- HUD Offers
    ["Random Brainrot"] = 3538728108,
    ["Ballerino Lololo"] = 3533817502,
    ["Tung Sahur"] = 3533817608,

    -- Map Offers
    ["Break Block"] = 3524818590,
    ["Gold Ballerina Cappuccina"] = 3527109775,
    ["Diamond Bananita Dolphinita"] = 3527109928,
})
