name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rokit
        env:
          GITHUB_PAT: ${{ github.token }}
        run: |
          curl -sSf https://raw.githubusercontent.com/rojo-rbx/rokit/main/scripts/install.sh | bash
          echo "$HOME/.rokit/bin" >> "$GITHUB_PATH"

      - name: Install Rokit tools
        timeout-minutes: 5
        run: rokit install --no-trust-check

      - name: Check
        timeout-minutes: 10
        run: sh scripts/check.sh
