return {
    Name = "GiveBrainrot",
    Aliases = {},
    Description = "Gives a player a brainrot.",
    Group = "Developer",
    Args = {
        {
            Type = "brainrot",
            Name = "Brainrot",
            Description = "The brainrot to give",
        },
        {
            Type = "player",
            Name = "Player",
            Description = "The player to give it to",
        },
    },
}
